### ISSUE TITLE
getDataTool function failing - 404 error

### ISSUE THREAD

**Issue by gleizerowicz** [Winvision/vsts-tasks#33]
Azure Cosmos DB Migration Tool Task fails with "Error: Parameter 'toolPath' cannot be null or empty."

running the release with System.Debug = true shows a 404 error when trying download the migration tool zip file:
2022-10-16T19:40:53.8790422Z ##[debug]Failed to download "5c797be1-b723-4cfc-889f-1267e3ae51c3" from "https://download.microsoft.com/download/E/1/4/E143A339-41AE-4E0E-9CC8-911C0B663478/dt-1.7.zip". Code(404) Message(Not Found)
2022-10-16T19:40:53.8793291Z ERR:Unexpected HTTP response: 404
2022-10-16T19:40:53.8793872Z ##[debug]task result: Failed

**Comment by meganadhan93** [comment]
Yes, started receiving same error ...

**Comment by eugeninm** [comment]
I'm having the same problem

**Comment by wynandjordaan** [comment]
Same issue, is there a way that we can force to use a previous version of the tool?

**Comment by LasseKlitgaard** [comment]
We have the same issue. Is this something that is being fixed anytime soon?

**Comment by meganadhan93** [comment]
Hello @ppluijten 

Download url is no more valid , please check .

https://github.com/Winvision/vsts-tasks/blob/831111f938143083b91f9b56e9b855b8ecd2e4c8/cosmosdb-tasks/Tasks/DataMigrationTool/datatoolDownloader.ts#L15

**Comment by wynandjordaan** [comment]
Has anyone come up with an alternative solution. We cannot go 10 days without hearing anything from anyone.

**Comment by isangines** [comment]
Having the same issue:

==============================================================================
Task         : Cosmos DB Data Migration Tool
Description  : With the Azure Cosmos DB Data Migration tool, you can easily migrate data to Azure Cosmos DB
Version      : 1.0.13
Author       : Winvision BV
Help         : [Support](https://github.com/Winvision/vsts-tasks)
==============================================================================
Downloading: https://download.microsoft.com/download/E/1/4/E143A339-41AE-4E0E-9CC8-911C0B663478/dt-1.7.zip
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:6768) Warning: Use Cipheriv for counter mode of aes-256-ctr

**ERR:Unexpected HTTP response: 404
##[error]Error: Parameter 'toolPath' cannot be null or empty.**

**Comment by rahim3216** [comment]
Any one have solution for that facing the same issue.
##[debug]Failed to download "0f6a0108-de44-4db0-97fc-b277bcccc154" from "https://download.microsoft.com/download/E/1/4/E143A339-41AE-4E0E-9CC8-911C0B663478/dt-1.7.zip". Code(404) Message(Not Found)

ERR:Unexpected HTTP response: 404
##[error]Error: Parameter 'toolPath' cannot be null or empty.

**Comment by smphayward** [comment]
Huge problem for us as well. Critical step in our pipeline is now failing as a result.

I've been trying to figure out what happened to dt-1.7.zip and if there is a newer version available.

It **might** be this:

[Azure DocumentDB Data Migration Tool](https://github.com/Azure/azure-documentdb-datamigrationtool/releases)

Current release is 1.8.3, though I don't see a 1.7 version so I can't be certain it's the same.

If it is the same tool and it's compatible, perhaps we could make a fork of this vsts-tasks git project and use the newest version of the exe in that fork.

**Comment by Arodriguez81** [comment]
In the meantime what we can do is to do it from cli until they fix it.

***Create a powershell task to download dt.
Invoke-WebRequest -Uri "https://github.com/Azure/azure-documentdb-datamigrationtool/releases/download/1.8.3/azure-documentdb-datamigrationtool-1.8.3.zip" -OutFile "$(System.DefaultWorkingDirectory)\dt-1.8.3.zip"
***Unzip it
steps:
- task: ExtractFiles@1
  displayName: 'Extract files '
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/dt-1.8.3.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)/dt-1.8.3'
***Command line
cd $(System.DefaultWorkingDirectory)/dt-1.8.3/azure-documentdb-datamigrationtool-1.8.3
dt (copy the command from desktop version view command once you have the connections setup and pasted here.) 
*** Run pipeline

**Comment by duyn9uyen** [comment]
@Arodriguez81, thanks for the idea. This worked for me.

```
- task: PowerShell@2
  displayName: 'Download azure-documentdb-datamigrationtool'
  inputs:
    targetType: 'inline'
	script: |
          Invoke-WebRequest -Uri "https://github.com/Azure/azure-documentdb-datamigrationtool/releases/download/1.8.3/azure-documentdb-datamigrationtool-1.8.3.zip" -OutFile "$(System.DefaultWorkingDirectory)\dt-1.8.3.zip"
- task: ExtractFiles@1
  displayName: 'Extract files '
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/dt-1.8.3.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)/dt-1.8.3'
- task: PowerShell@2
  displayName: 'Download azure-documentdb-datamigrationtool'
  inputs:
    targetType: 'inline'
      script: |
	cd $(System.DefaultWorkingDirectory)/dt-1.8.3/azure-documentdb-datamigrationtool-1.8.3
	./dt.exe /s:JsonFile /s.Files:"$(System.DefaultWorkingDirectory)/myJsonFiles/*.json" /t:DocumentDB /t.ConnectionString:"{ConnectionString}" /t.Collection:{collectionName} /t.UpdateExisting
```
